//>>built
require({cache:{"dojox/charting/axis2d/common":function(){define(["dojo/_base/lang","dojo/_base/window","dojo/dom-geometry","dojox/gfx","dojo/has"],function(p,l,h,g,f){var a=p.getObject("dojox.charting.axis2d.common",!0),e=function(d){d.marginLeft="0px";d.marginTop="0px";d.marginRight="0px";d.marginBottom="0px";d.paddingLeft="0px";d.paddingTop="0px";d.paddingRight="0px";d.paddingBottom="0px";d.borderLeftWidth="0px";d.borderTopWidth="0px";d.borderRightWidth="0px";d.borderBottomWidth="0px"};return p.mixin(a,
{createText:{gfx:function(d,b,c,k,t,w,v,x){return b.createText({x:c,y:k,text:w,align:t}).setFont(v).setFill(x)},html:function(d,b,c,k,t,w,v,x,u){b=l.doc.createElement("div");var r=b.style;d.getTextDir&&(b.dir=d.getTextDir(w));e(r);r.font=v;b.innerHTML=String(w).replace(/\s/g,"\x26nbsp;");r.color=x;r.position="absolute";r.left="-10000px";l.body().appendChild(b);var m=g.normalizedLength(g.splitFontString(v).size);if(!u)if(b.getBoundingClientRect){var q=b.getBoundingClientRect();q=q.width||q.right-q.left}else q=
h.getMarginBox(b).w;"rtl"==b.dir&&(c+=u?u:q);l.body().removeChild(b);r.position="relative";if(u)switch(r.width=u+"px",t){case "middle":r.textAlign="center";r.left=c-u/2+"px";break;case "end":r.textAlign="right";r.left=c-u+"px";break;default:r.left=c+"px",r.textAlign="left"}else switch(t){case "middle":r.left=Math.floor(c-q/2)+"px";break;case "end":r.left=Math.floor(c-q)+"px";break;default:r.left=Math.floor(c)+"px"}r.top=Math.floor(k-m)+"px";r.whiteSpace="nowrap";u=l.doc.createElement("div");r=u.style;
e(r);r.width="0px";r.height="0px";u.appendChild(b);d.node.insertBefore(u,d.node.firstChild);f("dojo-bidi")&&d.htmlElementsRegistry.push([u,c,k,t,w,v,x]);return u}}})})},"dojox/lang/functional":function(){define(["./functional/lambda","./functional/array","./functional/object"],function(p){return p})},"dojox/lang/functional/lambda":function(){define(["../..","dojo/_base/lang","dojo/_base/array"],function(p,l,h){var g=l.getObject("lang.functional",!0,p),f={},a=1<"ab".split(/a*/).length?String.prototype.split:
function(b){var c=this.split.call(this,b);(b=b.exec(this))&&0==b.index&&c.unshift("");return c},e=function(b){var c=[],k=a.call(b,/\s*->\s*/m);if(1<k.length)for(;k.length;)b=k.pop(),c=k.pop().split(/\s*,\s*|\s+/m),k.length&&k.push("(function("+c.join(", ")+"){ return ("+b+"); })");else if(b.match(/\b_\b/))c=["_"];else{k=b.match(/^\s*(?:[+*\/%&|\^\.=<>]|!=)/m);var t=b.match(/[+\-*\/%&|\^\.=<>!]\s*$/m);if(k||t)k&&(c.push("$1"),b="$1"+b),t&&(c.push("$2"),b+="$2");else{k=b.replace(/(?:\b[A-Z]|\.[a-zA-Z_$])[a-zA-Z_$\d]*|[a-zA-Z_$][a-zA-Z_$\d]*:|this|true|false|null|undefined|typeof|instanceof|in|delete|new|void|arguments|decodeURI|decodeURIComponent|encodeURI|encodeURIComponent|escape|eval|isFinite|isNaN|parseFloat|parseInt|unescape|dojo|dijit|dojox|window|document|'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"/g,
"").match(/([a-z_$][a-z_$\d]*)/gi)||[];var w={};h.forEach(k,function(v){w.hasOwnProperty(v)||(c.push(v),w[v]=1)})}}return{args:c,body:b}},d=function(b){return b.length?function(){var c=b.length-1,k=g.lambda(b[c]).apply(this,arguments);for(--c;0<=c;--c)k=g.lambda(b[c]).call(this,k);return k}:function(c){return c}};l.mixin(g,{rawLambda:function(b){return e(b)},buildLambda:function(b){b=e(b);return"function("+b.args.join(",")+"){return ("+b.body+");}"},lambda:function(b){if("function"==typeof b)return b;
if(b instanceof Array)return d(b);if(f.hasOwnProperty(b))return f[b];var c=e(b);return f[b]=new Function(c.args,"return ("+c.body+");")},clearLambdaCache:function(){f={}}});return g})},"dojox/lang/functional/array":function(){define(["dojo/_base/kernel","dojo/_base/lang","dojo/_base/array","./lambda"],function(p,l,h,g){var f={};l.mixin(g,{filter:function(a,e,d){"string"==typeof a&&(a=a.split(""));d=d||p.global;e=g.lambda(e);var b=[],c;if(l.isArray(a)){var k=0;for(c=a.length;k<c;++k){var t=a[k];e.call(d,
t,k,a)&&b.push(t)}}else if("function"==typeof a.hasNext&&"function"==typeof a.next)for(k=0;a.hasNext();)t=a.next(),e.call(d,t,k++,a)&&b.push(t);else for(k in a)k in f||(t=a[k],e.call(d,t,k,a)&&b.push(t));return b},forEach:function(a,e,d){"string"==typeof a&&(a=a.split(""));d=d||p.global;e=g.lambda(e);var b;if(l.isArray(a)){var c=0;for(b=a.length;c<b;e.call(d,a[c],c,a),++c);}else if("function"==typeof a.hasNext&&"function"==typeof a.next)for(c=0;a.hasNext();e.call(d,a.next(),c++,a));else for(c in a)c in
f||e.call(d,a[c],c,a);return d},map:function(a,e,d){"string"==typeof a&&(a=a.split(""));d=d||p.global;e=g.lambda(e);var b,c;if(l.isArray(a)){var k=Array(b=a.length);for(c=0;c<b;k[c]=e.call(d,a[c],c,a),++c);}else if("function"==typeof a.hasNext&&"function"==typeof a.next)for(k=[],c=0;a.hasNext();k.push(e.call(d,a.next(),c++,a)));else for(c in k=[],a)c in f||k.push(e.call(d,a[c],c,a));return k},every:function(a,e,d){"string"==typeof a&&(a=a.split(""));d=d||p.global;e=g.lambda(e);var b;if(l.isArray(a)){var c=
0;for(b=a.length;c<b;++c)if(!e.call(d,a[c],c,a))return!1}else if("function"==typeof a.hasNext&&"function"==typeof a.next)for(c=0;a.hasNext();){if(!e.call(d,a.next(),c++,a))return!1}else for(c in a)if(!(c in f||e.call(d,a[c],c,a)))return!1;return!0},some:function(a,e,d){"string"==typeof a&&(a=a.split(""));d=d||p.global;e=g.lambda(e);var b;if(l.isArray(a)){var c=0;for(b=a.length;c<b;++c)if(e.call(d,a[c],c,a))return!0}else if("function"==typeof a.hasNext&&"function"==typeof a.next)for(c=0;a.hasNext();){if(e.call(d,
a.next(),c++,a))return!0}else for(c in a)if(!(c in f)&&e.call(d,a[c],c,a))return!0;return!1}});return g})},"dojox/lang/functional/object":function(){define(["dojo/_base/kernel","dojo/_base/lang","./lambda"],function(p,l,h){var g={};l.mixin(h,{keys:function(f){var a=[],e;for(e in f)e in g||a.push(e);return a},values:function(f){var a=[],e;for(e in f)e in g||a.push(f[e]);return a},filterIn:function(f,a,e){e=e||p.global;a=h.lambda(a);var d={},b;for(b in f)if(!(b in g)){var c=f[b];a.call(e,c,b,f)&&(d[b]=
c)}return d},forIn:function(f,a,e){e=e||p.global;a=h.lambda(a);for(var d in f)d in g||a.call(e,f[d],d,f);return e},mapIn:function(f,a,e){e=e||p.global;a=h.lambda(a);var d={},b;for(b in f)b in g||(d[b]=a.call(e,f[b],b,f));return d}});return h})},"dojox/charting/bidi/_bidiutils":function(){define({reverseMatrix:function(p,l,h,g){var f=h.l-h.r;h=g?-1:1;var a=0,e=0,d=1;l=g?l.width+f:0;g=0;p.matrix&&(h*=Math.abs(p.matrix.xx),d=p.matrix.yy,a=p.matrix.xy,e=p.matrix.yx,g=p.matrix.xy);p.setTransform({xx:h,
xy:a,yx:e,yy:d,dx:l,dy:g})}})},"dojox/charting/bidi/axis2d/Default":function(){define(["dojo/_base/declare","dojo/dom-style"],function(p,l){return p(null,{labelTooltip:function(h,g,f,a,e,d){var b="rtl"==l.get(g.node,"direction"),c="rtl"==g.getTextDir(f);c&&!b&&(f="\x3cspan dir\x3d'rtl'\x3e"+f+"\x3c/span\x3e");!c&&b&&(f="\x3cspan dir\x3d'ltr'\x3e"+f+"\x3c/span\x3e");this.inherited(arguments)},_isRtl:function(){return this.chart.isRightToLeft()}})})},"dojox/charting/bidi/action2d/Tooltip":function(){define(["dojo/_base/declare",
"dojo/dom-style"],function(p,l){return p(null,{_recheckPosition:function(h,g,f){if(this.chart.isRightToLeft()){var a=this.chart.offsets.l-this.chart.offsets.r;"marker"==h.element?(g.x=this.chart.dim.width-h.cx+a,f[0]="before-centered",f[1]="after-centered"):"circle"==h.element?g.x=this.chart.dim.width-h.cx-h.cr+a:"bar"==h.element||"column"==h.element?(g.x=this.chart.dim.width-g.width-g.x+a,"bar"==h.element&&(f[0]="before-centered",f[1]="after-centered")):"candlestick"==h.element?g.x=this.chart.dim.width+
a-h.x:"slice"==h.element&&("before-centered"!=f[0]&&"after-centered"!=f[0]||f.reverse(),g.x=h.cx+(h.cx-g.x))}},_format:function(h){var g="rtl"==l.get(this.chart.node,"direction"),f="rtl"==this.chart.getTextDir(h);return f&&!g?"\x3cspan dir \x3d 'rtl'\x3e"+h+"\x3c/span\x3e":!f&&g?"\x3cspan dir \x3d 'ltr'\x3e"+h+"\x3c/span\x3e":h}})})},"dojox/charting/bidi/widget/Legend":function(){define("dojo/_base/declare dojo/dom dijit/registry dojo/_base/connect dojo/_base/array dojo/query".split(" "),function(p,
l,h,g,f,a){function e(d){return/^(ltr|rtl|auto)$/.test(d)?d:null}return p(null,{postMixInProperties:function(){if(this.chart)this.textDir=this.chart.textDir,g.connect(this.chart,"setTextDir",this,"_setTextDirAttr");else if(this.chartRef){var d=h.byId(this.chartRef);if(!d)if(d=l.byId(this.chartRef))d=h.byNode(d);else return;this.textDir=d.textDir;g.connect(d,"setTextDir",this,"_setTextDirAttr")}},_setTextDirAttr:function(d){null!=e(d)&&this.textDir!=d&&(this._set("textDir",d),d=a(".dojoxLegendText",
this._tr),f.forEach(d,function(b){b.dir=this.getTextDir(b.innerHTML,b.dir)},this))}})})},"dojox/charting/bidi/widget/Chart":function(){define(["dojo/_base/declare"],function(p){return p(null,{postMixInProperties:function(){this.textDir=this.params.textDir?this.params.textDir:this.params.dir},_setTextDirAttr:function(l){null!=(/^(ltr|rtl|auto)$/.test(l)?l:null)&&(this._set("textDir",l),this.chart.setTextDir(l))},_setDirAttr:function(l){this._set("dir",l);this.chart.setDir(l)}})})},"dojox/charting/bidi/action2d/ZoomAndPan":function(){define(["dojo/_base/declare"],
function(p){return p(null,{_getDelta:function(l){return this.inherited(arguments)*(this.chart.isRightToLeft()?-1:1)}})})},"*noref":1}});
define("dojox/charting/bidi/Chart","dojox/main dojo/_base/declare dojo/_base/lang dojo/dom-style dojo/_base/array dojo/sniff dojo/dom dojo/dom-construct dojox/gfx dojox/gfx/_gfxBidiSupport ../axis2d/common dojox/string/BidiEngine dojox/lang/functional dojo/dom-attr ./_bidiutils".split(" "),function(p,l,h,g,f,a,e,d,b,c,k,t,w,v,x){function u(m){return/^(ltr|rtl|auto)$/.test(m)?m:null}var r=new t;h.getObject("charting",!0,p);return l(null,{textDir:"",dir:"",isMirrored:!1,getTextDir:function(m){(m="auto"==
this.textDir?r.checkContextual(m):this.textDir)||(m=g.get(this.node,"direction"));return m},postscript:function(m,q){var n=q?q.textDir?u(q.textDir):"":"";this.textDir=n=n?n:g.get(this.node,"direction");this.surface.textDir=n;this.htmlElementsRegistry=[];this.truncatedLabelsRegistry=[];n="ltr";v.has(m,"direction")&&(n=v.get(m,"direction"));this.setDir(q?q.dir?q.dir:n:n)},setTextDir:function(m,q){if(m==this.textDir)return this;null!=u(m)&&(this.textDir=m,this.surface.setTextDir(m),this.truncatedLabelsRegistry&&
"auto"==m&&f.forEach(this.truncatedLabelsRegistry,function(n){var y=this.getTextDir(n.label);n.element.textDir!=y&&n.element.setShape({textDir:y})},this),q=w.keys(this.axes),0<q.length?(f.forEach(q,function(n,y,z){n=this.axes[n];n.htmlElements[0]&&(n.dirty=!0,n.render(this.dim,this.offsets))},this),this.title&&this._renderTitle(this.dim,this.offsets)):f.forEach(this.htmlElementsRegistry,function(n,y,z){y="auto"==m?this.getTextDir(n[4]):m;n[0].children[0]&&n[0].children[0].dir!=y&&(d.destroy(n[0].children[0]),
n[0].children[0]=k.createText.html(this,this.surface,n[1],n[2],n[3],n[4],n[5],n[6]).children[0])},this));return this},setDir:function(m){if("rtl"==m||"ltr"==m)this.dir!=m&&(this.dirty=this.isMirrored=!0),this.dir=m;return this},isRightToLeft:function(){return"rtl"==this.dir},applyMirroring:function(m,q,n){x.reverseMatrix(m,q,n,"rtl"==this.dir);g.set(this.node,"direction","ltr");return this},formatTruncatedLabel:function(m,q,n){this.truncateBidi(m,q,n)},truncateBidi:function(m,q,n){"gfx"==n&&(this.truncatedLabelsRegistry.push({element:m,
label:q}),"auto"==this.textDir&&m.setShape({textDir:this.getTextDir(q)}));"html"==n&&"auto"==this.textDir&&(m.children[0].dir=this.getTextDir(q))},render:function(){this.inherited(arguments);this.isMirrored=!1;return this},_resetLeftBottom:function(m){m.vertical&&this.isMirrored&&(m.opt.leftBottom=!m.opt.leftBottom)}})});