//>>built
define("dgrid/TouchScroll","dojo/_base/declare dojo/on ./util/touch ./util/has-css3 put-selector/put xstyle/css!./css/TouchScroll.css".split(" "),function(G,x,A,t,n){function B(b,a,e,f){var c=b.touchNode,g=l[b.id];if("object"!==typeof a){var d=a;var h=e;a=f;f=e=!0}else f="x"in a,e="y"in a,f&&e||(h=b.getScrollPosition()),d=f?a.x:h.x,h=e?a.y:h.y;c.style[m]=p+-d+"px,"+-h+"px"+r;g&&f&&b._scrollbarXNode&&(b._scrollbarXNode.style[m]=p+d*g.parentWidth/g.scrollWidth+"px,0"+r);g&&e&&b._scrollbarYNode&&(b._scrollbarYNode.style[m]=
p+"0,"+h*g.parentHeight/g.scrollHeight+"px"+r);x.emit(b.touchNode.parentNode,"scroll",{scrollLeft:d,scrollTop:h})}function E(b){return l[b.id]?H.exec(window.getComputedStyle(b.touchNode)[m]):C.exec(b.touchNode.style[m])}function I(b){var a=this.widget;a=[this.node,a._scrollbarXNode,a._scrollbarYNode];var e=a.length;this.timer&&(clearTimeout(this.timer),this.timer=null);for(this.transitionHandler&&this.transitionHandler.remove();e--;)a[e]&&(a[e].style[w+"Duration"]="0");b&&b.preserveScrollbars||n(this.node.parentNode,
".touchscroll-fadeout");delete this.resetEffects}function J(b){var a=b.widget,e=a.touchNode,f=a.id,c=0,g=0,d;if(A.countCurrentTouches(b,e)===a.touchesToScroll){if(d=E(a))c=+d[1],g=+d[2];if(d=l[f])d.resetEffects&&d.resetEffects({preserveScrollbars:!0}),e.style[m]=p+c+"px,"+g+"px"+r,y[f]=d;b=b.targetTouches[0];d=l[f]={widget:a,node:e,startX:c-b.pageX,startY:g-b.pageY,lastX:c,lastY:g,pageX:b.pageX,pageY:b.pageY,tickFunc:function(){var h=l[f],k;if(h){if(k=C.exec(h.node.style[m])){var q=+k[1];k=+k[2];
h.velX=q-h.lastX;h.velY=k-h.lastY;h.lastX=q;h.lastY=k}else h.lastX=h.lastY=0;h.timer=setTimeout(h.tickFunc,50)}}};d.timer=setTimeout(d.tickFunc,50)}}function K(b){var a=b.widget,e=a.id,f=a.touchesToScroll,c=l[e],g,d;if(c&&(g=A.countCurrentTouches(b,a.touchNode))===f){g=b.targetTouches;f=g[0];if(!c.scrollbarsShown&&(y[e]||Math.abs(f.pageX-c.pageX)>a.scrollThreshold||Math.abs(f.pageY-c.pageY)>a.scrollThreshold)){e=a.touchNode;var h=e.parentNode,k=h.offsetWidth-8,q=h.offsetHeight-8,u=c.scrollWidth=e.scrollWidth,
v=c.scrollHeight=e.scrollHeight,L=c.parentWidth=h.offsetWidth,M=c.parentHeight=h.offsetHeight;u>L?(a._scrollbarXNode||(d=n(h,"div.touchscroll-x")),d=a._scrollbarXNode=a._scrollbarXNode||n(d,"div.touchscroll-bar"),d.style.width=k*k/u+"px",d.style.left=e.offsetLeft+"px",n(h,".touchscroll-scrollable-x"),c.scrollableX=!0):n(h,"!touchscroll-scrollable-x");v>M?(a._scrollbarYNode||(d=n(h,"div.touchscroll-y")),d=a._scrollbarYNode=a._scrollbarYNode||n(d,"div.touchscroll-bar"),d.style.height=q*q/v+"px",d.style.top=
e.offsetTop+"px",n(h,".touchscroll-scrollable-y"),c.scrollableY=!0):n(h,"!touchscroll-scrollable-y");n(h,"!touchscroll-fadeout");c.scrollbarsShown=!0;for(d=g.length;d--;)g[d].touchScrolled=!0}c.scrollbarsShown&&(c.scrollableX||c.scrollableY)&&(b.preventDefault(),b=c.scrollableX?c.startX+f.pageX:0,f=c.scrollableY?c.startY+f.pageY:0,d=c.scrollableX?-(c.scrollWidth-c.parentWidth):0,c=c.scrollableY?-(c.scrollHeight-c.parentHeight):0,0<b?b/=2:b<d&&(b=d-(d-b)/2),0<f?f/=2:f<c&&(f=c-(c-f)/2),B(a,-b,-f))}else g>
f&&a.cancelTouchScroll()}function N(b){var a=b.widget,e=a.id;l[e]&&A.countCurrentTouches(b,a.touchNode)==a.touchesToScroll-1&&O(e)}function F(b,a,e){function f(){delete c.transitionHandler;c.resetEffects();delete l[b]}var c=l[b],g=c.widget,d=c.node,h=c.scrollableX?Math.max(Math.min(0,a),-(c.scrollWidth-c.parentWidth)):a,k=c.scrollableY?Math.max(Math.min(0,e),-(c.scrollHeight-c.parentHeight)):e;delete c.timer;h!=a||k!=e?(c.transitionHandler=x.once(d,P,f),d.style[w+"Duration"]=g.bounceDuration+"ms",
d.style[m]=p+h+"px,"+k+"px"+r,h!=a&&c.scrollableX&&(d=c.widget._scrollbarXNode,d.style[w+"Duration"]=g.bounceDuration+"ms",d.style[m]=a>h?p+"0,0"+r:p+(d.parentNode.offsetWidth-d.offsetWidth)+"px,0"+r),k!=e&&c.scrollableY&&(d=c.widget._scrollbarYNode,d.style[w+"Duration"]=g.bounceDuration+"ms",d.style[m]=e>k?p+"0,0"+r:p+"0,"+(d.parentNode.offsetHeight-d.offsetHeight)+"px"+r)):f()}function O(b){var a=l[b],e=y[b],f;delete y[b];a.timer&&clearTimeout(a.timer);a.resetEffects=I;if(f=C.exec(a.node.style[m])){var c=
+f[1];f=+f[2]}else c=f=0;!a.velX&&!a.velY||(0<=c||c<=-(a.scrollWidth-a.parentWidth))&&(0<=f||f<=-(a.scrollHeight-a.parentHeight))?F(b,c,f):(e&&(e.velX||e.velY)&&(0>=a.velX&&0>=e.velX||0<=a.velX&&0<=e.velX)&&(0>=a.velY&&0>=e.velY||0<=a.velY&&0<=e.velY)&&(a.velX=1.15*(a.velX+e.velX),a.velY=1.15*(a.velY+e.velY)),a.lastX=c,a.lastY=f,a.calcFunc=function(){var g=l[b],d;if(g){var h=g.widget;var k=h.glideDecel(g.velX);var q=h.glideDecel(g.velY);if(1<=Math.abs(k)||1<=Math.abs(q)){var u=g.lastX+k;var v=g.lastY+
q;if(0<u||u<-(g.scrollWidth-g.parentWidth))for(d=6;d--;)k=h.glideDecel(k);if(0<v||v<-(g.scrollHeight-g.parentHeight))for(d=6;d--;)q=h.glideDecel(q);B(h,-u,-v);g.lastX=u;g.lastY=v;g.velX=k;g.velY=q;g.timer=setTimeout(g.calcFunc,30)}else F(b,g.lastX,g.lastY)}},a.timer=setTimeout(a.calcFunc,30))}var l={},y={},C=/^translate(?:3d)?\((-?\d+)(?:\.\d*)?(?:px)?, (-?\d+)/,H=/^matrix\(1, 0, 0, 1, (-?\d+)(?:\.\d*)?(?:px)?, (-?\d+)/,D=t("css-transitions"),P=t("transitionend"),z=t("css-transforms");t=t("css-transforms3d");
if(t){var p="translate3d(";var r=",0)"}else z&&(p="translate(",r=")");if(!D||!p)return function(){};var m=t||z;m=!0===m?"transform":m+"Transform";var w=!0===D?"transition":D+"Transition";var Q=!0===z?"":"-"+z.toLowerCase()+"-";return G("dgrid.TouchScroll",null,{touchesToScroll:1,touchNode:null,scrollThreshold:10,bounceDuration:300,postCreate:function(){this._initTouch();this.inherited(arguments)},_initTouch:function(){function b(){f.cancelTouchScroll()}function a(g){return function(d){d.widget=f;
d.cancelTouchScroll=b;g.call(this,d)}}var e=this.touchNode=this.touchNode||this.containerNode,f=this;if(e&&e.parentNode){var c=e.parentNode;c.style.overflow="hidden";e.style[w+"Property"]=Q+"transform";e.style[w+"TimingFunction"]="cubic-bezier(0.33, 0.66, 0.66, 1)";this._touchScrollListeners=[x(c,"touchstart",a(J)),x(c,"touchmove",a(K)),x(c,"touchend,touchcancel",a(N))]}},destroy:function(){for(var b=this._touchScrollListeners.length;b--;)this._touchScrollListeners[b].remove();delete l[this.id];this.inherited(arguments)},
scrollTo:function(b){var a=l[this.id],e=this.touchNode,f=e.parentNode;!b.preserveMomentum&&a&&a.resetEffects&&a.resetEffects();b.x&&(b.x=Math.max(0,Math.min(b.x,e.scrollWidth-f.offsetWidth)));b.y&&(b.y=Math.max(0,Math.min(b.y,e.scrollHeight-f.offsetHeight)));B(this,b)},getScrollPosition:function(){var b=E(this);return b?{x:-b[1],y:-b[2]}:{x:0,y:0}},cancelTouchScroll:function(){var b=l[this.id];b&&(b.resetEffects?b.resetEffects():(b.timer&&clearTimeout(b.timer),n(b.node.parentNode,".touchscroll-fadeout")),
delete l[this.id])},glideDecel:function(b){return.9*b}})});